package com.stash.payments.ledger.service;

import com.stash.payments.ledger.domain.EntryRequest;

import java.util.List;
import java.util.UUID;

/**
 * Immutable command object passed to {@link LedgerService#writeTransaction}.
 *
 * @param transactionType       e.g. DEPOSIT, WITHDRAWAL, TRANSFER
 * @param transactionReference  STSH-yyyymm-XXXXXX; generated by caller
 * @param businessReferenceId   UUID of the triggering business object
 * @param businessReferenceType e.g. VAULT_DEPOSIT, PEER_TRANSFER
 * @param entries               two or more balanced entry requests
 * @param correlationId         request trace ID
 * @param narrative             human-readable description for ops
 */
public record LedgerWriteCommand(
        String             transactionType,
        String             transactionReference,
        UUID               businessReferenceId,
        String             businessReferenceType,
        List<EntryRequest> entries,
        String             correlationId,
        String             narrative
) {
    public LedgerWriteCommand {
        if (entries == null || entries.size() < 2) {
            throw new IllegalArgumentException(
                    "A ledger transaction requires at least two entries; got: " +
                    (entries == null ? "null" : entries.size()));
        }
        entries = List.copyOf(entries);
    }
}
