-- Migration: V1__create_user_module_users.sql
-- Creates the user_module schema and the users table per Schema doc §1.2.
--
-- Design decisions documented here:
--   - UUID v7 primary key: time-ordered, generated at the application layer
--     by shared/uuid-v7. The DB column is UUID type; the value is supplied
--     by the application on INSERT — no DB-side UUID generation function needed.
--   - email: lowercased at the application layer before storage; UNIQUE constraint
--     enforced here at the DB level.
--   - phone and ghana_card_number: PARTIAL unique indexes (WHERE IS NOT NULL)
--     so multiple users can have NULL in these columns simultaneously without
--     violating uniqueness. A standard UNIQUE constraint treats NULL as unequal
--     to NULL, but Postgres partial indexes give us the cleaner semantic:
--     "unique only when a value is actually present".
--   - kyc_status, subscription_tier, account_status: stored as VARCHAR with
--     CHECK constraints rather than Postgres ENUM types. Reason: adding a value
--     to a Postgres ENUM requires ALTER TYPE which takes an exclusive lock and
--     cannot be done inside a transaction. CHECK on VARCHAR is safe to change
--     via a normal migration.
--   - Soft delete: deleted_at IS NULL means active; non-NULL means deleted.
--     No hard deletes on user rows — the deletion_requests flow governs lifecycle.
--
-- Rollback strategy: forward-only. If a corrective change is needed,
-- write a V2 migration that alters or drops and recreates. Never edit
-- an applied migration file.

-- ── Schema ─────────────────────────────────────────────────────────────────

CREATE SCHEMA IF NOT EXISTS user_module;

-- ── Table ──────────────────────────────────────────────────────────────────

CREATE TABLE user_module.users (

    -- Primary key: UUID v7, generated by the application layer (shared/uuid-v7)
                                   id                      UUID            NOT NULL,

    -- Identity
                                   email                   VARCHAR(320)    NOT NULL,
                                   email_verified_at       TIMESTAMPTZ     NULL,
                                   password_hash           VARCHAR(255)    NOT NULL,
                                   password_changed_at     TIMESTAMPTZ     NULL,
                                   display_name            VARCHAR(100)    NOT NULL,

    -- Contact (optional until specific features require them)
                                   phone                   VARCHAR(20)     NULL,

    -- KYC
                                   ghana_card_number       VARCHAR(20)     NULL,
                                   kyc_status              VARCHAR(50)     NOT NULL DEFAULT 'PENDING',

    -- Subscription
                                   subscription_tier       VARCHAR(50)     NOT NULL DEFAULT 'FREE',

    -- Account lifecycle
                                   account_status          VARCHAR(50)     NOT NULL DEFAULT 'ACTIVE',
                                   referred_by_code        VARCHAR(50)     NULL,

    -- Timestamps
                                   created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
                                   deleted_at              TIMESTAMPTZ     NULL,

    -- ── Constraints ──────────────────────────────────────────────────────

                                   CONSTRAINT users_pkey
                                       PRIMARY KEY (id),

                                   CONSTRAINT users_email_unique
                                       UNIQUE (email),

                                   CONSTRAINT users_kyc_status_check
                                       CHECK (kyc_status IN (
                                                             'PENDING',
                                                             'SUBMITTED',
                                                             'APPROVED',
                                                             'REJECTED',
                                                             'RESUBMISSION_REQUIRED'
                                           )),

                                   CONSTRAINT users_subscription_tier_check
                                       CHECK (subscription_tier IN (
                                                                    'FREE',
                                                                    'PREMIUM'
                                           )),

                                   CONSTRAINT users_account_status_check
                                       CHECK (account_status IN (
                                                                 'ACTIVE',
                                                                 'SUSPENDED',
                                                                 'CLOSED'
                                           )),

                                   CONSTRAINT users_ghana_card_number_length_check
                                       CHECK (ghana_card_number IS NULL OR LENGTH(ghana_card_number) BETWEEN 10 AND 20)

);

-- ── Partial unique indexes ─────────────────────────────────────────────────

-- Unique phone, but only where a phone number is actually present.
-- Multiple users with phone = NULL do not conflict.
CREATE UNIQUE INDEX users_phone_unique_idx
    ON user_module.users (phone)
    WHERE phone IS NOT NULL;

-- Unique Ghana Card number, but only where one has been assigned (post-KYC).
-- Multiple users with ghana_card_number = NULL do not conflict.
CREATE UNIQUE INDEX users_ghana_card_number_unique_idx
    ON user_module.users (ghana_card_number)
    WHERE ghana_card_number IS NOT NULL;

-- ── Supporting indexes ─────────────────────────────────────────────────────

-- kyc_status: admin dashboard queries for 'who has SUBMITTED waiting review'
CREATE INDEX users_kyc_status_idx
    ON user_module.users (kyc_status);

-- account_status: operational queries (list all SUSPENDED accounts, etc.)
CREATE INDEX users_account_status_idx
    ON user_module.users (account_status);

-- Soft-delete filter: most queries add WHERE deleted_at IS NULL.
-- A partial index covering active rows keeps those queries fast.
CREATE INDEX users_active_idx
    ON user_module.users (created_at DESC)
    WHERE deleted_at IS NULL;

-- ── Comments ───────────────────────────────────────────────────────────────

COMMENT ON TABLE user_module.users IS
    'Canonical user account. One row per Stash customer. '
    'Soft-deleted via deleted_at; never hard-deleted. '
    'Schema doc §1.2.';

COMMENT ON COLUMN user_module.users.id IS
    'UUID v7 primary key — time-ordered. Generated by the application '
    'layer (shared/uuid-v7), never by the DB.';

COMMENT ON COLUMN user_module.users.email IS
    'Lowercased at the application layer before storage. '
    'RFC 5321 max length 320.';

COMMENT ON COLUMN user_module.users.password_hash IS
    'BCrypt hash at cost factor 12. Never logged, never returned to clients.';

COMMENT ON COLUMN user_module.users.password_changed_at IS
    'Updated on every password change. Used to invalidate refresh tokens '
    'issued before this timestamp.';

COMMENT ON COLUMN user_module.users.phone IS
    'E.164 format. Optional until certain features (e.g. mobile money) '
    'require it. Unique where non-NULL via partial index.';

COMMENT ON COLUMN user_module.users.ghana_card_number IS
    'Set only after KYC approval. Unique where non-NULL via partial index. '
    'Not stored in the KYC Service — that holds the raw submission; '
    'this column is the canonical approved value on the user record.';

COMMENT ON COLUMN user_module.users.kyc_status IS
    'PENDING → SUBMITTED → APPROVED | REJECTED | RESUBMISSION_REQUIRED. '
    'Transitions driven by the KYC Service publishing events.';

COMMENT ON COLUMN user_module.users.subscription_tier IS
    'FREE or PREMIUM. Default FREE.';

COMMENT ON COLUMN user_module.users.account_status IS
    'ACTIVE (normal), SUSPENDED (admin action), CLOSED (deletion complete). '
    'Default ACTIVE.';

COMMENT ON COLUMN user_module.users.deleted_at IS
    'NULL = active. Non-NULL = soft-deleted. Set by the deletion flow '
    'after the 30-day cool-off period. See user_module.deletion_requests.';