-- Migration: V1__create_transactions.sql
-- Creates the transaction schema and transaction.transactions table
-- per Schema doc §6.4.
--
-- Design decisions:
--   - This is the business-facing record. ledger.ledger_transactions is the
--     accounting record. They are linked by ledger_transaction_id (FK) and
--     by sharing the same transaction reference value (denormalised — not
--     a FK, just the same generated STSH-yyyymm-XXXXXX string written to
--     both rows in one atomic operation by the ledger write service,
--     v0.3-013). Support and the mobile 'my transactions' screen query
--     this table; the ledger integrity job queries ledger.ledger_transactions.
--
--   - FK to ledger.ledger_transactions: valid — same database. ON DELETE
--     RESTRICT: you must never destroy a ledger transaction that a
--     business transaction references.
--
--   - initiating_user_id and counterparty_user_id are logical references
--     to user_module.users.id (monolith-db). No FK across databases.
--
--   - gross_amount, fee_amount, net_amount are all BIGINT pesewas.
--     CHECK: net_amount = gross_amount - fee_amount enforced here because
--     if the write service ever miscalculates, the DB catches it
--     immediately rather than silently storing bad data. fee_amount >= 0
--     (fees are never negative). gross_amount > 0 (you cannot transact
--     zero). net_amount >= 0 (fees cannot exceed the gross amount —
--     a fee larger than the transaction amount would produce a negative
--     net, which is nonsensical and indicates a calculation bug).
--
--   - status mirrors the lifecycle: PENDING (created, awaiting provider
--     confirmation), COMPLETED (provider confirmed + ledger posted),
--     FAILED (provider declined or timeout — no ledger entries written),
--     REVERSED (completed but then unwound by a compensating transaction).
--
--   - idempotency_key stored here for audit and for the idempotency
--     enforcement layer (v0.3-007) to cross-reference. Not enforced as
--     UNIQUE here — idempotency.idempotency_keys (v0.3-005) is the
--     enforcement table; this column is the audit trail.
--
--   - completed_at is NULL until status reaches a terminal state
--     (COMPLETED, FAILED, REVERSED). The CHECK enforces this:
--     completed_at must be NULL when status is PENDING, and non-NULL
--     when COMPLETED or REVERSED. FAILED transactions may or may not
--     have a completed_at (provider may time out without a clear
--     terminal signal) — so FAILED is excluded from the non-NULL side.
--
-- Rollback strategy: forward-only.

CREATE SCHEMA IF NOT EXISTS transaction;

CREATE TABLE transaction.transactions (

    id                          UUID            NOT NULL,

    -- Customer-visible reference. Same value as
    -- ledger.ledger_transactions.transaction_reference for the linked
    -- accounting event. Generated by TransactionReferenceGenerator.
    reference                   VARCHAR(50)     NOT NULL,

    transaction_type            VARCHAR(50)     NOT NULL,

    -- Logical references — monolith-db, no FK possible.
    initiating_user_id          UUID            NOT NULL,
    counterparty_user_id        UUID            NULL,   -- NULL for self-only operations (deposit, withdrawal)

    gross_amount                BIGINT          NOT NULL,
    fee_amount                  BIGINT          NOT NULL DEFAULT 0,
    net_amount                  BIGINT          NOT NULL,

    status                      VARCHAR(50)     NOT NULL DEFAULT 'PENDING',

    external_provider           VARCHAR(50)     NULL,   -- PAYSTACK or NULL for internal-only
    external_reference          VARCHAR(255)    NULL,   -- Paystack transaction reference / transfer code

    -- Accounting link — same database, valid FK.
    ledger_transaction_id       UUID            NULL,   -- NULL until ledger is posted (PENDING state)

    correlation_id              VARCHAR(255)    NULL,
    idempotency_key             VARCHAR(255)    NULL,   -- Audit trail; enforcement is in idempotency.idempotency_keys

    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    completed_at                TIMESTAMPTZ     NULL,   -- NULL until COMPLETED or REVERSED

    CONSTRAINT transactions_pkey
        PRIMARY KEY (id),

    CONSTRAINT transactions_reference_uk
        UNIQUE (reference),

    CONSTRAINT transactions_ledger_transaction_fk
        FOREIGN KEY (ledger_transaction_id)
        REFERENCES ledger.ledger_transactions (id)
        ON DELETE RESTRICT,

    CONSTRAINT transactions_transaction_type_check
        CHECK (transaction_type IN (
            'DEPOSIT',
            'WITHDRAWAL',
            'TRANSFER',
            'SUSU_CONTRIBUTION',
            'SUSU_DISBURSEMENT',
            'VAULT_EARLY_EXIT_PENALTY',
            'FEE_COLLECTION',
            'INTEREST_ACCRUAL',
            'REVERSAL'
        )),

    CONSTRAINT transactions_status_check
        CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REVERSED')),

    CONSTRAINT transactions_external_provider_check
        CHECK (external_provider IS NULL OR external_provider IN ('PAYSTACK')),

    CONSTRAINT transactions_gross_amount_positive
        CHECK (gross_amount > 0),

    CONSTRAINT transactions_fee_amount_nonneg
        CHECK (fee_amount >= 0),

    CONSTRAINT transactions_net_amount_nonneg
        CHECK (net_amount >= 0),

    CONSTRAINT transactions_net_amount_calculation
        CHECK (net_amount = gross_amount - fee_amount),

    -- completed_at must be non-NULL for COMPLETED and REVERSED (terminal success states).
    -- PENDING and FAILED are excluded: PENDING is never terminal; FAILED may lack
    -- a clear completion signal from the provider.
    CONSTRAINT transactions_completed_at_terminal_check
        CHECK (
            (status IN ('COMPLETED', 'REVERSED') AND completed_at IS NOT NULL)
            OR status NOT IN ('COMPLETED', 'REVERSED')
        )
);

-- Schema doc §6.4 index: support lookups by reference
-- (covered by the unique constraint — no separate index needed)

-- Schema doc §6.4 index: 'my transactions' screen — newest first per user
CREATE INDEX transactions_initiating_user_id_created_at_idx
    ON transaction.transactions (initiating_user_id, created_at DESC);

-- Status + created_at — ops queries ('show all PENDING transactions older than 10 minutes')
CREATE INDEX transactions_status_created_at_idx
    ON transaction.transactions (status, created_at DESC)
    WHERE status = 'PENDING';

-- External reference lookup — Paystack webhook handler resolves its
-- reference back to our transaction row (v0.3-018)
CREATE INDEX transactions_external_reference_idx
    ON transaction.transactions (external_provider, external_reference)
    WHERE external_reference IS NOT NULL;

COMMENT ON TABLE transaction.transactions IS
    'Business-facing transaction records. Every money movement creates one '
    'row here. Links to the accounting record via ledger_transaction_id. '
    'Schema doc §6.4.';

COMMENT ON COLUMN transaction.transactions.reference IS
    'Customer-visible reference (STSH-yyyymm-XXXXXX). Same value as '
    'ledger.ledger_transactions.transaction_reference — written to both '
    'tables in one atomic operation by the ledger write service (v0.3-013). '
    'Not a FK; denormalised for query performance.';

COMMENT ON COLUMN transaction.transactions.ledger_transaction_id IS
    'NULL while status=PENDING (ledger not yet posted). Set to the '
    'ledger_transactions.id once Paystack confirms and entries are written.';

COMMENT ON COLUMN transaction.transactions.net_amount IS
    'gross_amount - fee_amount. Enforced by CHECK constraint. '
    'Displayed to the user as "amount received" or "amount sent".';

COMMENT ON COLUMN transaction.transactions.idempotency_key IS
    'Audit copy of the client-supplied Idempotency-Key header. '
    'Enforcement is in idempotency.idempotency_keys (v0.3-005), '
    'not on this column.';

COMMENT ON COLUMN transaction.transactions.external_reference IS
    'Provider-assigned reference — Paystack transaction ID or transfer code. '
    'Used by the webhook handler (v0.3-018) to match an inbound event '
    'back to this row via the external_reference index.';
