package com.stash.kyc.storage;

import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.nio.file.NoSuchFileException;

@RestController
@RequestMapping("/internal/local-storage")
public class LocalStorageUploadController {

    private final LocalStorageUploadService uploadService;

    public LocalStorageUploadController(LocalStorageUploadService uploadService) {
        this.uploadService = uploadService;
    }

    @PutMapping(value = "/upload/{*path}", consumes = MediaType.ALL_VALUE)
    public ResponseEntity<Void> upload(@PathVariable("path") String path,
                                       HttpServletRequest request) throws IOException {
        // {*path} captures everything after /upload/ including slashes; strip the leading slash.
        String relativePath = path.startsWith("/") ? path.substring(1) : path;
        byte[] body = request.getInputStream().readAllBytes();
        uploadService.store(relativePath, body);
        return ResponseEntity.status(HttpStatus.CREATED).build();
    }

    /**
     * Serves a stored document for viewing. This is the download counterpart to
     * {@code /upload/**} and backs the signed view URLs generated by
     * {@link LocalFilesystemObjectStorage#generateSignedDownloadUrl}. Reached by
     * the admin console (proxied through the monolith) when rendering KYC images.
     */
    @GetMapping("/view/{*path}")
    public ResponseEntity<byte[]> view(@PathVariable("path") String path) throws IOException {
        String relativePath = path.startsWith("/") ? path.substring(1) : path;
        try {
            byte[] body = uploadService.read(relativePath);
            return ResponseEntity.ok()
                    .contentType(contentTypeFor(relativePath))
                    .body(body);
        } catch (NoSuchFileException e) {
            return ResponseEntity.notFound().build();
        }
    }

    private static MediaType contentTypeFor(String path) {
        String lower = path.toLowerCase();
        if (lower.endsWith(".png")) return MediaType.IMAGE_PNG;
        if (lower.endsWith(".gif")) return MediaType.IMAGE_GIF;
        // All KYC document keys are stored as .jpg (see KycSubmissionService);
        // default to JPEG so the admin console <img> renders correctly.
        return MediaType.IMAGE_JPEG;
    }
}
