-- Migration: V2__create_ledger_transactions.sql
-- Creates ledger.ledger_transactions per Schema doc §6.2.
--
-- Design decisions:
--   - This table is conceptually append-only: once a ledger_transaction is
--     written and its entries posted, neither the transaction nor its entries
--     should ever be updated. No REVOKE is issued here (unlike ledger_entries
--     in V3 which has a hard REVOKE UPDATE/DELETE). The reason: the outbox
--     relay (v0.3-006) needs to UPDATE status on ledger_transactions to mark
--     events as dispatched — so a full REVOKE breaks the outbox. Instead,
--     the application layer enforces append-only semantics; the nightly
--     integrity job (v0.3-022) catches any drift.
--
--   - status is not in Schema doc §6.2 but is required by this issue's
--     acceptance criteria. It represents the lifecycle of the accounting
--     event: PENDING (entries not yet written), POSTED (double-entry
--     complete and balanced), FAILED (entries never wrote — rolled back),
--     REVERSED (a compensating transaction was applied). This is a tracked
--     addition to the Schema doc — same as the v0.2 KYC reconciliation
--     pattern; the Schema doc §6.2 should be updated to include it.
--
--   - transaction_reference format: STSH-yyyymm-XXXXXX where XXXXXX is
--     a 6-character alphanumeric suffix. Generated by
--     TransactionReferenceGenerator (see Step 3). The UNIQUE constraint
--     on this column enforces collision-freedom at the DB layer.
--
--   - business_reference_id + business_reference_type form a polymorphic
--     logical reference — the business object (vault deposit, susu round,
--     peer transfer) that triggered this accounting event. No FK because
--     the business object may live in a different schema or service.
--
--   - amount is the gross amount in pesewas; it is NOT the same as the
--     ledger entry amounts, but must equal SUM of DEBIT entries (and by
--     double-entry invariant also the SUM of CREDIT entries).
--
-- Rollback strategy: forward-only.

CREATE TABLE ledger.ledger_transactions (

    id                          UUID            NOT NULL,

    transaction_type            VARCHAR(50)     NOT NULL,
    business_reference_id       UUID            NULL,       -- Logical FK to triggering business object
    business_reference_type     VARCHAR(50)     NULL,       -- e.g. VAULT_DEPOSIT, PEER_TRANSFER, SUSU_CONTRIBUTION

    transaction_reference       VARCHAR(50)     NOT NULL,   -- STSH-yyyymm-XXXXXX; customer-visible
    amount                      BIGINT          NOT NULL,   -- Pesewas; CHECK > 0; gross amount

    status                      VARCHAR(50)     NOT NULL DEFAULT 'PENDING',

    correlation_id              VARCHAR(255)    NULL,
    narrative                   VARCHAR(255)    NULL,

    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT ledger_transactions_pkey
        PRIMARY KEY (id),

    CONSTRAINT ledger_transactions_reference_uk
        UNIQUE (transaction_reference),

    CONSTRAINT ledger_transactions_transaction_type_check
        CHECK (transaction_type IN (
            'DEPOSIT',
            'WITHDRAWAL',
            'TRANSFER',
            'SUSU_CONTRIBUTION',
            'SUSU_DISBURSEMENT',
            'VAULT_EARLY_EXIT_PENALTY',
            'FEE_COLLECTION',
            'INTEREST_ACCRUAL',
            'REVERSAL'
        )),

    CONSTRAINT ledger_transactions_business_reference_type_check
        CHECK (business_reference_type IS NULL OR business_reference_type IN (
            'VAULT_DEPOSIT',
            'VAULT_WITHDRAWAL',
            'VAULT_EARLY_EXIT',
            'PEER_TRANSFER',
            'SUSU_CONTRIBUTION',
            'SUSU_DISBURSEMENT',
            'INTEREST_ACCRUAL',
            'REVERSAL'
        )),

    CONSTRAINT ledger_transactions_amount_positive
        CHECK (amount > 0),

    CONSTRAINT ledger_transactions_status_check
        CHECK (status IN ('PENDING', 'POSTED', 'FAILED', 'REVERSED'))
);

-- Lookups by business object — "show all ledger events for vault deposit X"
CREATE INDEX ledger_transactions_business_ref_idx
    ON ledger.ledger_transactions (business_reference_type, business_reference_id)
    WHERE business_reference_id IS NOT NULL;

-- Status + created_at — for the nightly integrity job and ops queries
CREATE INDEX ledger_transactions_status_created_at_idx
    ON ledger.ledger_transactions (status, created_at DESC);

COMMENT ON TABLE ledger.ledger_transactions IS
    'Atomic, immutable accounting events. Each row groups the ledger_entries '
    'that move money between accounts. Once status=POSTED the row is never '
    'updated (enforced at application layer; verified by nightly integrity job). '
    'Schema doc §6.2 (status column is a tracked addition — see migration comment).';

COMMENT ON COLUMN ledger.ledger_transactions.transaction_reference IS
    'Customer-visible reference. Format: STSH-yyyymm-XXXXXX. '
    'Generated by TransactionReferenceGenerator; UNIQUE enforced at DB layer.';

COMMENT ON COLUMN ledger.ledger_transactions.amount IS
    'Gross amount in pesewas. Must equal SUM(ledger_entries.amount WHERE direction=DEBIT) '
    'for this transaction. Verified at write time and by the nightly integrity job.';

COMMENT ON COLUMN ledger.ledger_transactions.status IS
    'PENDING: transaction inserted, entries not yet written. '
    'POSTED: all entries written and balanced (double-entry invariant holds). '
    'FAILED: entries were never written — transaction rolled back. '
    'REVERSED: a compensating REVERSAL transaction was applied.';
